#!/usr/bin/env python3
"""Fetch view_num for multiple xiaohongshu (小红书) creator-portal topics
via XYS_-signed search.

Calls POST https://creator.xiaohongshu.com/api/galaxy/v2/creator/servicegw/v2/search/topics
with XYS_ / x-s-common / traceid headers generated by `xhshow`, validates that
each matched topic id equals the canonical id, and appends ONE record per
invocation to `xhs_topic.json` (a JSON list, accumulating one entry per run —
same pattern as `douyin.json`).

The three tracked topics (see TOPICS below) write into a single record:

    {"ts": ..., "sgz_tag_view_num": ..., "yqmr_tag_view_num": ..., "fyzs_tag_view_num": ...}

If ANY topic fails (mismatch / no data / invalid view_num / network error)
the whole run aborts before appending — we never record partial data.

Output on stdout (single line, for log/debug):
  {"ts": ..., "sgz_tag_view_num": ..., "yqmr_tag_view_num": ..., "fyzs_tag_view_num": ...}

Env:
  XHS_COOKIE       - full cookie header (a1, web_session, webId, webBuild, ...).
                     Required. xhshow uses the FULL cookie dict (not just a1).
  XHS_DATA_FILE    - output path (default: xhs_topic.json in cwd)
  XHS_SSL_VERIFY   - "0" disables TLS verification (macOS Python cert workaround).
                     Default: "1".
  UA               - optional user-agent override.
  TIMEOUT          - seconds (default 30).
"""
import json
import os
import ssl
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

from xhshow import Xhshow

ENDPOINT = "https://creator.xiaohongshu.com/api/galaxy/v2/creator/servicegw/v2/search/topics"

DEFAULT_UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36"
)

# The three tracked topics. `key` is the field name written to xhs_topic.json.
# Canonical topic ids are taken from creator.xiaohongshu.com's search response
# and validated on every fetch — mismatch aborts the whole run.
TOPICS: list[dict[str, str]] = [
    {
        "keyword":  "尚公主",
        "topic_id": "5fb167d700000000010072c4",
        "key":      "sgz_tag_view_num",
    },
    {
        "keyword":  "昀牵孟绕",
        "topic_id": "660796630000000002024e5a",
        "key":      "yqmr_tag_view_num",
    },
    {
        "keyword":  "扶摇直尚",
        "topic_id": "67d0f2b3000000000401ed01",
        "key":      "fyzs_tag_view_num",
    },
    {
        "keyword":  "孟子义李昀锐",
        "topic_id": "65a62cad000000003f03df2c",
        "key":      "mzylyr_tag_view_num",
    },
    {
        "keyword":  "李昀锐孟子义",
        "topic_id": "65a6ad41000000003100d0fa",
        "key":      "lyrmzy_tag_view_num",
    },
]

# macOS Python ships without a current CA bundle; allow opting out.
if os.environ.get("XHS_SSL_VERIFY", "1") == "0":
    _ctx = ssl.create_default_context()
    _ctx.check_hostname = False
    _ctx.verify_mode = ssl.CERT_NONE
    SSL_CTX = _ctx
else:
    SSL_CTX = None

# Module-level xhshow client. It manages internal crypto state per instance.
xhshow = Xhshow()


def _parse_cookie_dict(cookie_str: str) -> dict[str, str]:
    """Parse full Cookie header into a dict. xhshow needs ALL cookies
    (a1, web_session, webId, webBuild, ...); not just a1."""
    out: dict[str, str] = {}
    for part in cookie_str.split(";"):
        if "=" not in part:
            continue
        k, v = part.strip().split("=", 1)
        if k:
            out[k] = v
    return out


def _fetch_search_topics(
    keyword: str, cookies: dict[str, str], ua: str, timeout: int
) -> dict:
    body = {
        "keyword": keyword,
        "topic_round_start_time": int(time.time() * 1000),
        "content": "aaa",
    }

    # xhshow produces: x-s, x-s-common, x-t, x-b3-traceid, x-xray-traceid,
    #                  x-mns, xy-direction
    sig = xhshow.sign_headers_post(uri=ENDPOINT, cookies=cookies, payload=body)

    req = urllib.request.Request(
        ENDPOINT,
        data=json.dumps(body, ensure_ascii=False, separators=(",", ":")).encode("utf-8"),
        headers={
            "User-Agent": ua,
            "Content-Type": "application/json",
            "Origin": "https://creator.xiaohongshu.com",
            "Referer": "https://creator.xiaohongshu.com/",
            **sig,
        },
        method="POST",
    )
    # Re-attach Cookie header (xhshow signs with cookies but doesn't add it
    # to the returned headers dict).
    req.add_header("Cookie", "; ".join(f"{k}={v}" for k, v in cookies.items()))

    opener_kw = {"timeout": timeout}
    if SSL_CTX is not None:
        opener_kw["context"] = SSL_CTX
    with urllib.request.urlopen(req, **opener_kw) as resp:
        return json.loads(resp.read().decode("utf-8"))


def _match_topic(data: dict, keyword: str, expected_topic_id: str) -> dict:
    """Pull out the canonical topic_info_dto for `keyword` and validate id.

    Returns the inner dto on success. Raises ValueError on any mismatch /
    empty result / invalid view_num.
    """
    # Response shape (galaxy gateway):
    #   {"code":0,"success":true,"data":{"topics":[{"topic_info_dto":{...},
    #                                               "audio_visuals":[...]}]}}
    # Each item is wrapped in {"topic_info_dto": {...}, "audio_visuals": [...]};
    # unwrap to the inner dto for direct field access.
    raw_items = (data.get("data") or {}).get("topics") or []
    dtos = [
        item["topic_info_dto"] if isinstance(item, dict) and "topic_info_dto" in item
        else item
        for item in raw_items
    ]
    if not dtos:
        raise ValueError(
            f"NOT_FOUND: response={json.dumps(data, ensure_ascii=False)[:500]}"
        )

    match = next((t for t in dtos if t.get("name") == keyword), dtos[0])
    if match.get("name") != keyword:
        print(
            f"NAME_MISMATCH: got {match.get('name')!r}, expected {keyword!r}; "
            f"using first result",
            file=sys.stderr,
        )

    topic_id = match.get("id", "")
    if topic_id != expected_topic_id:
        raise ValueError(
            f"TOPIC_ID_MISMATCH: got {topic_id!r}, "
            f"expected {expected_topic_id!r}"
        )

    view_num = match.get("view_num")
    if not isinstance(view_num, (int, float)) or view_num < 0:
        raise ValueError(f"INVALID_VIEW_NUM: {view_num!r}")

    return match


def _append_record(data_file: Path, record: dict) -> None:
    """Append one record to data_file (JSON list). Same shape as douyin.json."""
    if data_file.exists():
        try:
            data = json.loads(data_file.read_text(encoding="utf-8"))
            if not isinstance(data, list):
                print(
                    f"WARN: {data_file} is not a list (got {type(data).__name__}); "
                    f"reinitializing",
                    file=sys.stderr,
                )
                data = []
        except json.JSONDecodeError as e:
            print(
                f"WARN: {data_file} is not valid JSON ({e}); reinitializing",
                file=sys.stderr,
            )
            data = []
    else:
        data = []
    data.append(record)
    data_file.write_text(
        json.dumps(data, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def _fetch_one(
    topic: dict[str, str], cookies: dict[str, str], ua: str, timeout: int
) -> int:
    """Fetch + validate one topic; return its view_num.

    Raises on any error so the caller can abort the whole run.
    """
    keyword = topic["keyword"]
    try:
        data = _fetch_search_topics(keyword, cookies, ua, timeout)
    except (urllib.error.URLError, TimeoutError) as e:
        raise RuntimeError(f"FETCH_ERROR ({keyword}): {e}") from e

    match = _match_topic(data, keyword, topic["topic_id"])
    return int(match["view_num"])


def main() -> int:
    cookie_str = os.environ.get("XHS_COOKIE", "").strip()
    data_file = Path(os.environ.get("XHS_DATA_FILE", "xhs_topic.json"))
    ua = os.environ.get("UA", DEFAULT_UA)
    timeout = int(os.environ.get("TIMEOUT", "30"))

    if not cookie_str:
        print("ERROR: XHS_COOKIE not set", file=sys.stderr)
        return 2

    cookies = _parse_cookie_dict(cookie_str)
    if not cookies:
        print("ERROR: XHS_COOKIE contains no key=value pairs", file=sys.stderr)
        return 2

    record: dict[str, int] = {"ts": int(time.time())}
    for topic in TOPICS:
        try:
            view_num = _fetch_one(topic, cookies, ua, timeout)
        except (ValueError, RuntimeError) as e:
            # Any single-topic failure aborts the whole run; we never record
            # partial data.
            print(f"ERROR ({topic['keyword']}): {e}", file=sys.stderr)
            return 1
        record[topic["key"]] = view_num
        print(
            f"{topic['keyword']!r} ({topic['topic_id']}) → "
            f"{topic['key']}={view_num}",
            file=sys.stderr,
        )

    _append_record(data_file, record)

    # Echo to stdout for log/debug visibility in Actions output.
    print(json.dumps(record, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())